insert into notetaker_customvocabulary (id, campaign_id, term, note) values (1, 1, 'Halia', 'Enemy');
insert into notetaker_customvocabulary (id, campaign_id, term, note) values (2, 2, 'Gwyn', 'Location');
insert into notetaker_customvocabulary (id, campaign_id, term, note) values (3, 3, 'Halia', 'Deity');
insert into notetaker_customvocabulary (id, campaign_id, term, note) values (4, 4, 'Halia', 'Location');
insert into notetaker_customvocabulary (id, campaign_id, term, note) values (5, 5, 'Zaki', 'Dungeon');
insert into notetaker_customvocabulary (id, campaign_id, term, note) values (6, 6, 'Alis', 'Enemy');
insert into notetaker_customvocabulary (id, campaign_id, term, note) values (7, 7, 'Gwyn', 'Dungeon');
insert into notetaker_customvocabulary (id, campaign_id, term, note) values (8, 8, 'Halia', 'NPC');
insert into notetaker_customvocabulary (id, campaign_id, term, note) values (9, 9, 'Sister Garaele', 'Enemy');
insert into notetaker_customvocabulary (id, campaign_id, term, note) values (10, 10, 'Halia', 'Deity');
insert into notetaker_customvocabulary (id, campaign_id, term, note) values (11, 11, 'Zaki', 'Deity');
insert into notetaker_customvocabulary (id, campaign_id, term, note) values (12, 12, 'Halia', 'Dungeon');
insert into notetaker_customvocabulary (id, campaign_id, term, note) values (13, 13, 'Sama', 'Enemy');
insert into notetaker_customvocabulary (id, campaign_id, term, note) values (14, 14, 'Alis', 'Deity');
insert into notetaker_customvocabulary (id, campaign_id, term, note) values (15, 15, 'Sama', 'Enemy');
insert into notetaker_customvocabulary (id, campaign_id, term, note) values (16, 16, 'Sister Garaele', 'Dungeon');
insert into notetaker_customvocabulary (id, campaign_id, term, note) values (17, 17, 'Alis', 'Dungeon');
insert into notetaker_customvocabulary (id, campaign_id, term, note) values (18, 18, 'Alis', 'Location');
insert into notetaker_customvocabulary (id, campaign_id, term, note) values (19, 19, 'Gwyn', 'Location');
insert into notetaker_customvocabulary (id, campaign_id, term, note) values (20, 20, 'Sister Garaele', 'Enemy');
insert into notetaker_customvocabulary (id, campaign_id, term, note) values (21, 21, 'Gwyn', 'Location');
insert into notetaker_customvocabulary (id, campaign_id, term, note) values (22, 22, 'Ool', 'Dungeon');
insert into notetaker_customvocabulary (id, campaign_id, term, note) values (23, 23, 'Ool', 'NPC');
insert into notetaker_customvocabulary (id, campaign_id, term, note) values (24, 24, 'Illithinoch', 'Deity');
insert into notetaker_customvocabulary (id, campaign_id, term, note) values (25, 25, 'Halia', 'Location');
insert into notetaker_customvocabulary (id, campaign_id, term, note) values (26, 26, 'Halia', 'Deity');
insert into notetaker_customvocabulary (id, campaign_id, term, note) values (27, 27, 'Gwyn', 'Dungeon');
insert into notetaker_customvocabulary (id, campaign_id, term, note) values (28, 28, 'Sama', 'Enemy');
insert into notetaker_customvocabulary (id, campaign_id, term, note) values (29, 29, 'Gwyn', 'Location');
insert into notetaker_customvocabulary (id, campaign_id, term, note) values (30, 30, 'Grunk', 'NPC');
