from django.db import models
import os

class Campaign(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name

class Session(models.Model):
    campaign = models.ForeignKey(Campaign, on_delete=models.CASCADE, related_name='sessions', null=True, blank=True)
    title = models.CharField(max_length=255, help_text="e.g., DND P3P3 2026-01-30")
    date_played = models.DateField(null=True, blank=True)
    
    # File handling
    audio_file = models.FileField(upload_to='session_audio/', help_text="The original MP3 recording")
    
    # Transcription Data (AssemblyAI)
    assembly_id = models.CharField(max_length=100, blank=True, null=True, help_text="ID from AssemblyAI for polling/reference")
    raw_transcript = models.TextField(blank=True, null=True, help_text="The full diarized transcript text")
    
    # Summary Data (Gemini)
    summary_markdown = models.TextField(blank=True, null=True, help_text="The structured markdown generated by Gemini")
    
    # Metadata
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    # Status tracking (helpful for UI spinners later)
    STATUS_CHOICES = [
        ('pending', 'Pending Upload'),
        ('transcribing', 'Transcribing'),
        ('summarizing', 'Summarizing'),
        ('completed', 'Completed'),
        ('error', 'Error'),
    ]
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')

    def __str__(self):
        return f"{self.title} ({self.date_played})"

    class Meta:
        ordering = ['-date_played', '-created_at']

class CustomVocabulary(models.Model):
    """
    Stores the D&D specific terms (Zaki, Ool, etc.) 
    so you can edit them in the Django Admin instead of hardcoding in scripts.
    """
    campaign = models.ForeignKey(Campaign, on_delete=models.CASCADE, related_name='vocabulary', null=True, blank=True)
    term = models.CharField(max_length=100)
    
    def __str__(self):
        return self.term

    class Meta:
        verbose_name_plural = "Custom Vocabularies"