# Generated by Django 4.2.28 on 2026-02-13 18:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notetaker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid'), ('trialing', 'Trialing'), ('inactive', 'Inactive')], default='inactive', max_length=20)),
                ('plan_tier', models.CharField(choices=[('free', 'Free Tier'), ('basic', 'Basic Tier'), ('pro', 'Pro Tier')], default='free', max_length=20)),
                ('monthly_audio_minutes_used', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minutes of AssemblyAI transcription used this cycle.', max_digits=8)),
                ('audio_minutes_limit', models.IntegerField(default=60, help_text='Max audio minutes allowed per billing cycle.')),
                ('summaries_generated_count', models.IntegerField(default=0, help_text='Number of summaries generated this cycle.')),
                ('billing_cycle_anchor', models.DateTimeField(blank=True, help_text='When the usage quotas should reset to zero.', null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False, help_text='True if user canceled but retains access until the period ends.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
