# Generated by Django 4.2.28 on 2026-02-13 21:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notetaker', '0003_alter_subscription_options_subscription_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summary',
            options={'verbose_name_plural': 'Summaries'},
        ),
        migrations.AlterField(
            model_name='subscription',
            name='monthly_audio_minutes_used',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minutes of transcription used this cycle.', max_digits=8),
        ),
    ]
