# Generated by Django 4.2.28 on 2026-02-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notetaker', '0004_alter_summary_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='audio_file',
            field=models.FileField(upload_to='notetaker/recordings'),
        ),
    ]
