# Generated by Django 4.2.28 on 2026-02-15 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notetaker', '0005_alter_recording_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recording', to='notetaker.session'),
        ),
    ]
