# Generated by Django 4.2.28 on 2026-02-15 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notetaker', '0006_alter_recording_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='subscription',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='notetaker.subscription'),
            preserve_default=False,
        ),
    ]
