# Generated by Django 4.2.28 on 2026-02-21 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notetaker', '0007_campaign_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='audio_file',
            field=models.FileField(upload_to='notetaker/recordings', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])]),
        ),
    ]
