# Generated by Django 6.0.3 on 2026-03-06 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notetaker', '0008_alter_recording_audio_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcription',
            name='utterances_json',
        ),
    ]
