# Generated by Django 6.0.3 on 2026-03-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notetaker', '0009_remove_transcription_utterances_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
