# Generated by Django 6.0.3 on 2026-03-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notetaker', '0010_transcription_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcription',
            old_name='processed_at',
            new_name='submitted_at',
        ),
        migrations.AddField(
            model_name='transcription',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcription',
            name='processing_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
